messages/main/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import UserRegView, MessageView, MSGLoginView, RegDoneView
from .views import logoutnlogin, MessageDoneView

app_name = 'main'
urlpatterns = [
        path('', MessageView.as_view(), name='index'),
        path('login/', MSGLoginView.as_view(), name='login'),
        path('logout/', logoutnlogin, name='logout'),
        path('register/', UserRegView.as_view(), name='register'),
        path('register/done/', RegDoneView.as_view(), name ='register_done'),
        path('message/done/', MessageDoneView.as_view(), name ='message_done')
        ]

messages/messages/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

messages/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from .utilities import post_save_dispacher

class Message(models.Model):
    text = models.TextField(max_length=500, verbose_name='Текст')
    email = models.EmailField(max_length=20, verbose_name='Email')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Отправитель')
    sent_to = models.DateField(auto_now_add=True, verbose_name='Отправленно')
    sent_email = models.BooleanField(default=False)

    def __str__(self):
        return 'message from {} sent: {}'.format(self.user, self.sent_to)

    class Meta:
        verbose_name_plural = 'Собщение'
        verbose_name = 'Собщения'
        ordering = ['-sent_to']


post_save.connect(post_save_dispacher, sender=Message)

messages/main/forms.py
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django import forms
from .models import Message


class UserRegForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html()
    )
    password2 = forms.CharField(
        label='Пароль (повторно)',
        widget=forms.PasswordInput,
        help_text='Введите пароль повторно для проверки'
    )

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1']:
            password_validation.validate_password(cd['password1'])
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Пароль не подходит')
        return cd['password1']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        labels = {
            'username': 'Имя пользователя',
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }

class MessageForm(forms.ModelForm):
    
    class Meta:
        model = Message
        fields = ('email', 'text')

messages/main/views.py
from django.contrib.auth.views import LoginView, logout_then_login
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from main.forms import UserRegForm, MessageForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.models import User


class MSGLoginView(LoginView):
    template_name = 'main/login.html'
    
def logoutnlogin(request):
    return logout_then_login(request)

class UserRegView(CreateView):
    template_name = 'main/register.html'
    form_class = UserRegForm
    success_url = reverse_lazy('register_done')

class RegDoneView(TemplateView):
    template_name = 'main/register_done.html'
    success_url = reverse_lazy('index')

class MessageView(LoginRequiredMixin, CreateView):
    template_name = 'main/index.html'
    form_class = MessageForm
    success_url = reverse_lazy('message_done')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        uid = self.request.user.id
        user = User.objects.get(pk=uid)
        msgs = user.message_set.all()[:5]
        context['msgs'] = msgs
        return context

    def form_valid(self, form):
        """Add to the form data about the user who sent the message """
        form.instance.user = self.request.user
        return super().form_valid(form)
    

class MessageDoneView(LoginRequiredMixin, TemplateView):
    template_name = 'main/message_done.html'

messages/main/templates/layout/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}Главная{% endblock %} - Сообщения</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
    </head>
    <body class="container">
        <header class="mb-4">
            <h1 class="display-1 text-center">Сообщения</h1>
        </header>
            <section class="col border py-2">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
            </section>
        </div>
    </body>
</html>

messages/main/templates/main/index.html
{% extends "layout/base.html"  %}

{% load bootstrap4 %}

{% block title %}Сообщение{% endblock %}

{% block content %}

<div class="row">
    <div class="col mb-3">
        <p>Привет {{ request.user.username }}</p>
        <p>Отправь сообщение администатору</p>
        <p><a href="{% url 'main:logout' %}">Выход</a></p>
    </div>
</div>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit="Отправить" %}{% endbuttons %}
    </form>

    <h1>Ваши посленднии сообщения</h1>
    <ul class="list-group">
        {% for msg in msgs %}
        <li class="list-group-item">{{ msg.sent_to }} - {{ msg.text|truncatewords:10}} | 
            {% if msg.sent_email %} Сообщение отправленно на email {% else %} Сообщение не тправленно на email {% endif %}</li>
        {% endfor %}
    </ul>
{% endblock %}

messages/main/templates/main/login.html
{% extends "layout/base.html"  %}
{% load bootstrap4 %}

{% block title %}Вход{% endblock %}

{% block content %}

<div class="row">
    <div class="col mb-5">
        <h1>Вход</h1>
    </div>
</div>

<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% buttons submit="Войти" %}{% endbuttons %}
</form>

<p>Регистрация пользователя</p>
<p><a href="{% url 'main:register' %}">Регистрация</a></p>
{% endblock %}

messages/main/templates/main/message_done.html
{% extends "layout/base.html"  %}
{% load bootstrap4 %}

{% block title %}Сообщение отправленно{% endblock %}

{% block content %}


<h1>Сообщение успешно отправленно</h1>
<p><a href="{% url 'main:index' %}">Отправить ещё</a></p>
<p><a href="{% url 'main:logout' %}">Выход</a></p>
{% endblock %}

messages/main/templates/main/register.html
{% extends "layout/base.html"  %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}

<div class="row">
    <div class="col mb-5">
        <h1>Регистрация пользователя</h1>
    </div>
</div>


<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit="Зарегистрироваться" %}{% endbuttons %}
</form>

{% endblock %}

messages/main/templates/main/register_done.html
{% extends "layout/base.html"  %}
{% load bootstrap4 %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}

<h1>Регистрация успешно завершена</h1>

<p><a href="{% url 'main:logout' %}">Вход</a></p>


{% endblock %}